# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c92bad32bc3f310ea9a65680eb2e40806ad6873c11b73ae38aa5eb5dca982bff5f4d6bec7b0af1a2a077a96c36b8a13bcb2c5457ebf575148a17ed1d97264bc

test:
  secret_key_base: 0145c3029e744e6e4f82345827385d06d48bf97616753c3df1917c200230d5f1cc41a1dfdbad0254bbf512e021d21f67af4d849422164d23ae5ed31a9a9c4b79

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
